# Netlify Deploy Configuration

[build]
  command = "cd frontend && npm ci && npm run build"
  publish = "frontend/build"

[build.environment]
  REACT_APP_API_URL = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200